image:
  name: coala-tslint-angular-image
  version: 0.1
  maintainer: jayvdb@gmail.com
  python_version: 3.6
  node_version: 10
  parent: djangomobans/lint-image
  npm:
    - csscomb
    - sass-lint
    - tslint
    - codelyzer
    - tslint-eslint-rules
    - eslint
    - babel-eslint
    - eslint-plugin-import
    - typescript-eslint-parser eslint-plugin-typescript
    - eslint-plugin-markdown
    - eslint-plugin-html eslint-plugin-protractor
    - typescript@3.1.1
    - '@angular/compiler'
    - '@angular/core'
    - rxjs
    - zone.js
  omit:
    expose: true
  inherit:
    cmd: true

requires:
  - https://github.com/django-mobans/docker-mobans

configuration:
  configuration: .moban.yaml
  template_dir:
    - 'docker-mobans:.moban.dt/'
targets:
  - Dockerfile: Dockerfile.jj2
  - .dockerfile_lint_rules.yaml: dockerfile_lint_rules.yaml.jj2
  - .gitlab-ci.yml: gitlab-ci.yml.jj2
  - .travis.yml: travis.yml.jj2
copy:
  - .coafile: .coafile
  - .gitignore: .gitignore
  - hooks/build: hooks/build
