sudo: false
dist: xenial
language: generic
services: docker

env:
  global:
    - IMAGE_NAME=coala-tslint-angular-image:this

install:
  - hooks/build

script:
  - docker images
  - docker run -v=$(pwd):/app --workdir=/app djangomobans/lint-image

notifications:
  email: false
